=== Willy93-coder/lenguajeMarcas/actividad_13/actividad13.dtd
<!ELEMENT email (mensaje+)>
<!ELEMENT mensaje (remite, destinatario, texto)>
<!ELEMENT remite (email_remitente)>
<!ELEMENT email_remitente (#PCDATA)>
<!ELEMENT destinatario (email_destinatario)>
<!ELEMENT email_destinatario (#PCDATA)>
<!ELEMENT texto (parrafo+)>
<!ELEMENT parrafo (#PCDATA)>
<!ATTLIST mensaje asunto CDATA #REQUIRED>
<!ATTLIST destinatario nombre CDATA #REQUIRED>
<!ATTLIST remite nombre CDATA #REQUIRED>

=== Willy93-coder/lenguajeMarcas/actividad_13/actividad13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email SYSTEM "actividad13.dtd">
<email>
    <mensaje>
        <remite nombre="Alfredo Reino">
            <email_remitente>alf@ibium.com</email_remitente>
        </remite>
        <destinatario nombre="Bill Clinton">
            <email_destinatario>president@whitehouse.gov</email_destinatario>
        </destinatario>
        <asunto tema="Hola Bill">
            <texto>
                <parrafo>¿Hola qué tal?...</parrafo>
            </texto>
        </asunto>
    </mensaje>
</email>
