=== Willy93-coder/lenguajeMarcas/actividad_14/actividad14.dtd
<!ELEMENT arboles (arbol+)>
<!ELEMENT arbol (nombre_comun?, vegetacion?, altura?, forma_estructura?, color_primavera?, color_otonio?, resistencia_heladas?)>
<!ATTLIST arbol nombre CDATA #REQUIRED>
<!ELEMENT nombre_comun (#PCDATA)>
<!ELEMENT vegetacion (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT forma_estructura (#PCDATA)>
<!ELEMENT color_primavera (#PCDATA)>
<!ELEMENT color_otonio (#PCDATA)>
<!ELEMENT resistencia_heladas (#PCDATA)>

=== Willy93-coder/lenguajeMarcas/actividad_14/actividad14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles SYSTEM "actividad14.dtd">
<arboles>
    <arbol nombre="Acer monspessulanum">
        <nombre_comun>Arce de Montpellier, Arce menor</nombre_comun>
        <vegetacion>Caducifolio</vegetacion>
        <altura>De 6 a 10 metros</altura>
        <forma_estructura>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</forma_estructura>
        <color_primavera>Haz verde brillante, envés verde blanquecino</color_primavera>
        <resistencia_heladas>Heladas fuertes (hasta -15ºC)</resistencia_heladas>
    </arbol>
    <arbol nombre="Olea europea">
        <nombre_comun>Olivo</nombre_comun>
        <vegetacion>Perenne</vegetacion>
        <altura>De 8 a 15 metros</altura>
        <forma_estructura>Copa irregular. Tronco principal irregular con bifurcaciones.</forma_estructura>
    </arbol>
    <arbol nombre="Ramaje tortuoso">
        <color_primavera>Haz verde oscuro, envés verde plateado</color_primavera>
        <resistencia_heladas>Heladas medias (hasta -10ºC)</resistencia_heladas>
    </arbol>
    <arbol nombre="Platanus orientalis">
        <nombre_comun>Platano</nombre_comun>
        <vegetacion>Caducifolio</vegetacion>
        <altura>De 20 a 25 metros</altura>
        <forma_estructura>Copa ovoidal. Tronco principal recto. Ramaje expandido</forma_estructura>
        <color_primavera>Haz verde medio, enves verde claro</color_primavera>
        <color_otonio>Ocre</color_otonio>
        <resistencia_heladas>Heladas fuertes (hasta -20ºC)</resistencia_heladas>
    </arbol>
    <arbol nombre="Quercus ilex">
        <nombre_comun>Encina</nombre_comun>
        <vegetacion>Perenne</vegetacion>
        <altura>En torno a 25 metros</altura>
        <forma_estructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma_estructura>
        <color_primavera>Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</color_primavera>
        <resistencia_heladas>Heladas fuertes (hasta -15ºC)</resistencia_heladas>
    </arbol>
</arboles>
