=== Willy93-coder/lenguajeMarcas/actividad_23/actividad23.dtd
<!ELEMENT facturas (factura)>
<!ELEMENT factura (datos_empresa, pedido, datos_cliente, datos_factura, total_factura)>
<!ELEMENT datos_empresa (nombre_empresa, calle, datos_origen, cif, contacto)>
<!ELEMENT nombre_empresa (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT datos_origen (poblacion_empresa, codigo_postal_empresa)>
<!ELEMENT poblacion_empresa (#PCDATA)>
<!ELEMENT codigo_postal_empresa (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT contacto (telefono, fax)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT pedido (fecha, numero_pedido, forma_pago)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT forma_pago (#PCDATA)>
<!ELEMENT datos_cliente (nombre_cliente, datos_envio)>
<!ELEMENT nombre_cliente (#PCDATA)>
<!ELEMENT datos_envio (direccion_envio, poblacion_cliente, codigo_postal_cliente, provincia_cliente)>
<!ELEMENT direccion_envio (calle_cliente, numero_calle, escalera)>
<!ELEMENT calle_cliente (#PCDATA)>
<!ELEMENT numero_calle (#PCDATA)>
<!ELEMENT escalera (#PCDATA)>
<!ELEMENT poblacion_cliente (#PCDATA)>
<!ELEMENT codigo_postal_cliente (#PCDATA)>
<!ELEMENT provincia_cliente (#PCDATA)>
<!ELEMENT datos_factura (datos_producto+)>
<!ELEMENT datos_producto (descripcion, cantidad, precio, iva, importe)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT total_factura (base_imponible, iva, cuota_iva)>
<!ELEMENT base_imponible (#PCDATA)>
<!ELEMENT cuota_iva (#PCDATA)>
<!ATTLIST factura numero CDATA #REQUIRED>
<!ATTLIST datos_cliente numero CDATA #REQUIRED>
<!ATTLIST escalera letra CDATA #REQUIRED>
<!ATTLIST datos_producto referencia CDATA #REQUIRED>
<!ATTLIST total_factura total CDATA #REQUIRED>

=== Willy93-coder/lenguajeMarcas/actividad_23/actividad23.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "actividad23.dtd">
<?xml-stylesheet href="actividad23.xsl" type="text/xsl"?>
<facturas>
    <factura numero='999'>
        <datos_empresa>
            <nombre_empresa>Equipos Digitales S.L.</nombre_empresa>
            <calle>Avenida Valladolid</calle>
            <datos_origen>
                <poblacion_empresa>Madrid </poblacion_empresa>
                <codigo_postal_empresa>28015</codigo_postal_empresa>
            </datos_origen>
            <cif>Q-9876543</cif>
            <contacto>
                <telefono>91.777.66.88</telefono>
                <fax>91.777.66.99</fax>
            </contacto>
        </datos_empresa>
        <pedido>
            <fecha>12-01-2005</fecha>
            <numero_pedido>731</numero_pedido>
            <forma_pago>EFECTIVO</forma_pago>
        </pedido>
        <datos_cliente numero='879'>
            <nombre_cliente>Darío Bueno Gutiérrez</nombre_cliente>
            <datos_envio>
                <direccion_envio>
                    <calle_cliente>Av. Oporto</calle_cliente>
                    <numero_calle>7 </numero_calle>
                    <escalera letra='d'> 4</escalera>
                </direccion_envio>
                <poblacion_cliente>Madrid</poblacion_cliente>
                <codigo_postal_cliente>28043</codigo_postal_cliente>
                <provincia_cliente>Madrid</provincia_cliente>
            </datos_envio>
        </datos_cliente>
        <datos_factura>
            <datos_producto referencia="MII9300F/8">
                <descripcion>MICRO PENTIUM IV 3000MHZ FB800</descripcion>
                <cantidad>1</cantidad>
                <precio>230</precio>
                <iva>16, 0</iva>
                <importe>266,80</importe>
            </datos_producto>
            <datos_producto referencia="MB8QDIP4">
                <descripcion>PLACA BASE QDI P4</descripcion>
                <cantidad>1</cantidad>
                <precio>180</precio>
                <iva>16, 0</iva>
                <importe>208,80</importe>
            </datos_producto>
            <datos_producto referencia="MEDD512M32">
                <descripcion>DIMM DDR 512MB 3200</descripcion>
                <cantidad>2</cantidad>
                <precio>40</precio>
                <iva>16, 0</iva>
                <importe>92,80</importe>
            </datos_producto>
            <datos_producto referencia="HD250GSA7">
                <descripcion>DISCO DURO 250GB S-ATA 7200</descripcion>
                <cantidad>4</cantidad>
                <precio>120</precio>
                <iva>16, 0</iva>
                <importe>556,80</importe>
            </datos_producto>
        </datos_factura>
        <total_factura total="1125,20">
            <base_imponible>970, 00</base_imponible>
            <iva>16, 0</iva>
            <cuota_iva>155, 20</cuota_iva>
        </total_factura>
    </factura>
</facturas>
